---
title: "flat_first.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- 
Run this 'development' chunk

Store every call to library() that you need to run chunks line by line, as in a classical Rmd for analysis
-->

```{r development, include=FALSE}
library(testthat)
```

<!--
# Description of your package

This will fill the description of your package.
Fill and run the content of this chunk, before anything else. 

Note: when you will use other flat templates, this part will be in a separate file. Do not be surprised!
--> 

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "systemdR",
    Description = "systemdR: an R package for managing systemd service and timers in linux.",
    `Authors@R` = c(
       person("Yanhua", "Zheng", email = "zyh3084989256@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-1103-9579"))
    )
  )
)
# Define License with use_*_license()
usethis::use_mit_license("YanhuaZheng")
#‘R6’ ‘fs’ ‘glue’
usethis::use_package("R6")
usethis::use_package("fs")
usethis::use_package("glue")
```

# ServiceClass
    
```{r function-ServiceClass}
#' ServiceClass
#' 
#' ServiceClass： this is an R6 object for systemd service create and run
#' @field Unit character Unit options of service file
#' @field Service character Service options of service file
#' @field Install character Install options of service file
#' @field servicename character name of service
#' @field save_dir character save_dir of created service file
#
#' @return R6 object
#' 
#' @export
ServiceClass <- R6::R6Class(
  "ServiceClass",
  public = list(
    Unit = NULL,Service = NA,
    Install= NA,
    servicename = NA,
    save_dir = NA,

#' @param Unit character Unit options of service file
#' @param Service character Service options of service file
#' @param Install character Install options of service file
#' @param servicename character name of service
#' @param save_dir character save_dir of created service file
  initialize = function( Unit = NULL,
                         Service = NA,
                         Install= c("WantedBy=multi-user.target"),
                         servicename = "temple",
                         save_dir = getwd()){
      self$Unit <- c("[Unit]",Unit)
      self$Service <- c("[Service]",Service)
      self$Install <- c("[Install]",Install)
      self$servicename <- servicename
      self$save_dir <- save_dir
      self$info()
    },
#' @method object info
#' @return NULL
    info = function(){
      message("BagginsClass：I am going on an adventure! this is an R6 object for rnaseq upstream workflow ")
    },
#' @method create service
#' 
#' @return NULL
    create = function(){
      if (!dir.exists(self$save_dir)){
        fs::dir_create(self$save_dir)
      }
      cat(c(self$Unit,self$Service,self$Install), 
          sep = "\n", 
          file = paste0(self$save_dir,"/",self$servicename,".service"))
    },
#' @method run service
#' 
#' @return NULL

    service_run = function(){
      message("copy to /etc/systemd/system/")
      servicefile <- paste0(self$save_dir,"/",self$servicename,".service")
      servicetitle <- paste0(sself$servicename,".service")
      if (file.exists(servicefile)){
        system(glue::glue("sudo cp -r {servicefile} /etc/systemd/system/"))
        system("sudo systemctl daemon-reload")
        system("sudo systemctl start {self$servicename}.service")
      } else {
        stop("service file not found")
      }
    },

#' @method service control
#' @param mod the mod of service control
#' @return NULL
   service_control = function(mod = c("stop","restart","enable","disable","status")){
        system("sudo systemctl {mod} {self$servicename}.service")
   }
)
)
 
```
  
```{r example-ServiceClass}
ServiceClass$new()
```
  
```{r tests-ServiceClass}
test_that("ServiceClass works", {
  expect_true(inherits(ServiceClass, "R6ClassGenerator")) 
})
```
  
# TimerClass
    
```{r function-TimerClass}
#' TimerClass
#' 
#' TimerClass： this is an R6 object for systemd timer create and run
#' @field Unit character Unit options of timer file
#' @field Timer character timer options of timer file
#' @field Install character Install options of timer file
#' @field timername character name of timer
#' @field save_dir character save_dir of created timer file
#
#' @return R6 object
#' 
#' @export
TimerClass <- R6::R6Class(
  "TimerClass",
  public = list(
    Unit = NULL,Timer = NA,
    Install= NA,
    timername = NA,
    save_dir = NA,

#' @param Unit character Unit options of timer file
#' @param Timer character timer options of timer file
#' @param Install character Install options of timer file
#' @param timername character name of timer
#' @param save_dir character save_dir of created timer file
  initialize = function( Unit = NULL,
                         Timer = NA,
                         Install= c("WantedBy=multi-user.target"),
                         timername = "temple",
                         save_dir = getwd()){
      self$Unit <- c("[Unit]",Unit)
      self$Timer <- c("[Timer]",Timer)
      self$Install <- c("[Install]",Install)
      self$timername <- timername
      self$save_dir <- save_dir
      self$info()
    },
#' @method object info
#' 
#' @return NULL
    info = function(){
      message("BagginsClass：I am going on an adventure! this is an R6 object for rnaseq upstream workflow ")
    },
#' @method create timer
#' @return NULL
    create = function(){
      if (!dir.exists(self$save_dir)){
        fs::dir_create(self$save_dir)
      }
      cat(c(self$Unit,self$Timer,self$Install), 
          sep = "\n", 
          file = paste0(self$save_dir,"/",self$timername,".timer"))
    },
#' @method run timer
#' @return NULL

    timer_run = function(){
      message("copy to /etc/systemd/system/")
      timerfile <- paste0(self$save_dir,"/",self$timername,".timer")
      timertitle <- paste0(sself$timername,".timer")
      if (file.exists(timerfile)){
        system(glue::glue("sudo cp -r {timerfile} /etc/systemd/system/"))
        system("sudo systemctl daemon-reload")
        system("sudo systemctl start {self$timername}.timer")
      } else {
        stop("timer file not found")
      }
    },

#' @method timer control
#' @param mod the mod of timer control
#' @return NULL
   timer_control = function(mod = c("stop","restart","enable","disable","status")){
        system("sudo systemctl {mod} {self$timername}.timer")
   }
)
)
 
```
  
```{r example-TimerClass}
TimerClass$new()
```
  
```{r tests-TimerClass}
test_that("TimerClass works", {
  expect_true(inherits(TimerClass, "R6ClassGenerator")) 
})
```
  



```{r development-inflate, eval=TRUE}
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_first.Rmd")
```

<!-- 
- Verify your `"DESCRIPTION"` file has been updated
- Verify your function is in `"R/"` directory
- Verify your test is in `"tests/testthat/"` directory
- Verify this Rmd appears in `"vignettes/"` directory 
-->
