# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' ServiceClass
#' 
#' ServiceClass： this is an R6 object for systemd service create and run
#' @field Unit character Unit options of service file
#' @field Service character Service options of service file
#' @field Install character Install options of service file
#' @field servicename character name of service
#' @field save_dir character save_dir of created service file
#
#' @return R6 object
#' 
#' @export
#' @examples
#' ServiceClass$new()
ServiceClass <- R6::R6Class(
  "ServiceClass",
  public = list(
    Unit = NULL,Service = NA,
    Install= NA,
    servicename = NA,
    save_dir = NA,

#' @param Unit character Unit options of service file
#' @param Service character Service options of service file
#' @param Install character Install options of service file
#' @param servicename character name of service
#' @param save_dir character save_dir of created service file
  initialize = function( Unit = NULL,
                         Service = NA,
                         Install= c("WantedBy=multi-user.target"),
                         servicename = "temple",
                         save_dir = getwd()){
      self$Unit <- c("[Unit]",Unit)
      self$Service <- c("[Service]",Service)
      self$Install <- c("[Install]",Install)
      self$servicename <- servicename
      self$save_dir <- save_dir
      self$info()
    },
#' @method object info
#' @return NULL
    info = function(){
      message("BagginsClass：I am going on an adventure! this is an R6 object for rnaseq upstream workflow ")
    },
#' @method create service
#' 
#' @return NULL
    create = function(){
      if (!dir.exists(self$save_dir)){
        fs::dir_create(self$save_dir)
      }
      cat(c(self$Unit,self$Service,self$Install), 
          sep = "\n", 
          file = paste0(self$save_dir,"/",self$servicename,".service"))
    },
#' @method run service
#' 
#' @return NULL

    service_run = function(){
      message("copy to /etc/systemd/system/")
      servicefile <- paste0(self$save_dir,"/",self$servicename,".service")
      servicetitle <- paste0(sself$servicename,".service")
      if (file.exists(servicefile)){
        system(glue::glue("sudo cp -r {servicefile} /etc/systemd/system/"))
        system("sudo systemctl daemon-reload")
        system("sudo systemctl start {self$servicename}.service")
      } else {
        stop("service file not found")
      }
    },

#' @method service control
#' @param mod the mod of service control
#' @return NULL
   service_control = function(mod = c("stop","restart","enable","disable","status")){
        system("sudo systemctl {mod} {self$servicename}.service")
   }
)
)
 
