# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' TimerClass
#' 
#' TimerClass： this is an R6 object for systemd timer create and run
#' @field Unit character Unit options of timer file
#' @field Timer character timer options of timer file
#' @field Install character Install options of timer file
#' @field timername character name of timer
#' @field save_dir character save_dir of created timer file
#
#' @return R6 object
#' 
#' @export
#' @examples
#' TimerClass$new()
TimerClass <- R6::R6Class(
  "TimerClass",
  public = list(
    Unit = NULL,Timer = NA,
    Install= NA,
    timername = NA,
    save_dir = NA,

#' @param Unit character Unit options of timer file
#' @param Timer character timer options of timer file
#' @param Install character Install options of timer file
#' @param timername character name of timer
#' @param save_dir character save_dir of created timer file
  initialize = function( Unit = NULL,
                         Timer = NA,
                         Install= c("WantedBy=multi-user.target"),
                         timername = "temple",
                         save_dir = getwd()){
      self$Unit <- c("[Unit]",Unit)
      self$Timer <- c("[Timer]",Timer)
      self$Install <- c("[Install]",Install)
      self$timername <- timername
      self$save_dir <- save_dir
      self$info()
    },
#' @method object info
#' 
#' @return NULL
    info = function(){
      message("BagginsClass：I am going on an adventure! this is an R6 object for rnaseq upstream workflow ")
    },
#' @method create timer
#' @return NULL
    create = function(){
      if (!dir.exists(self$save_dir)){
        fs::dir_create(self$save_dir)
      }
      cat(c(self$Unit,self$Timer,self$Install), 
          sep = "\n", 
          file = paste0(self$save_dir,"/",self$timername,".timer"))
    },
#' @method run timer
#' @return NULL

    timer_run = function(){
      message("copy to /etc/systemd/system/")
      timerfile <- paste0(self$save_dir,"/",self$timername,".timer")
      timertitle <- paste0(sself$timername,".timer")
      if (file.exists(timerfile)){
        system(glue::glue("sudo cp -r {timerfile} /etc/systemd/system/"))
        system("sudo systemctl daemon-reload")
        system("sudo systemctl start {self$timername}.timer")
      } else {
        stop("timer file not found")
      }
    },

#' @method timer control
#' @param mod the mod of timer control
#' @return NULL
   timer_control = function(mod = c("stop","restart","enable","disable","status")){
        system("sudo systemctl {mod} {self$timername}.timer")
   }
)
)
 
